#!/usr/bin/env bash

# Update the package list
sudo apt-get update -y

# Install Nginx
sudo apt-get install -y nginx

# Create the Hello World index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure a 301 redirect
sudo bash -c 'echo "        location /redirect_me {" >> /etc/nginx/sites-available/default'
sudo bash -c 'echo "                 return 301 https://www.youtube.com/watch?v=3lFkDc6dFoY;" >> /etc/nginx/sites-available/default'
sudo bash -c 'echo "        }" >> /etc/nginx/sites-available/default'

# Create the custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure the custom 404 page
sudo sed -i '/^server {/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                 root /var/www/html;\n                 internal;\n        }' /etc/nginx/sites-available/default

# Restart Nginx
sudo service nginx restart

