#!/usr/bin/env bash
# Install Nginx
sudo apt-get update -y
sudo apt-get install -y nginx

# Create Hello World index page
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure 301 redirect
sudo sed -i '/^server {/a \        location /redirect_me {\n                 return 301 https://www.youtube.com/watch?v=3lFkDc6dFoY;\n        }' /etc/nginx/sites-enabled/default

# Create custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html

# Configure custom 404 page
sudo sed -i '/^server {/a \        error_page 404 /custom_404.html;\n        location = /custom_404.html {\n                 root /var/www/html;\n                 internal;\n        }' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart

